/*
 *  Copyright The Shufflecake Project Authors (2022)
 *  Copyright The Shufflecake Project Contributors (2022)
 *  Copyright Contributors to the The Shufflecake Project.
 *  
 *  See the AUTHORS file at the top-level directory of this distribution and at
 *  <https://www.shufflecake.net/permalinks/shufflecake-userland/AUTHORS>
 *  
 *  This file is part of the program dm-sflc, which is part of the Shufflecake 
 *  Project. Shufflecake is a plausible deniability (hidden storage) layer for 
 *  Linux. See <https://www.shufflecake.net>.
 *  
 *  This program is free software: you can redistribute it and/or modify it 
 *  under the terms of the GNU General Public License as published by the Free 
 *  Software Foundation, either version 3 of the License, or (at your option) 
 *  any later version. This program is distributed in the hope that it will be 
 *  useful, but WITHOUT ANY WARRANTY; without even the implied warranty of 
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General 
 *  Public License for more details. You should have received a copy of the 
 *  GNU General Public License along with this program. 
 *  If not, see <https://www.gnu.org/licenses/>.
 */

/*****************************************************
 *                  INCLUDE SECTION                  *
 *****************************************************/

#include <linux/slab.h>

#include "rand.h"
#include "log/log.h"

/*****************************************************
 *                     CONSTANTS                     *
 *****************************************************/

/*****************************************************
 *                 PRIVATE VARIABLES                 *
 *****************************************************/

/*****************************************************
 *           PRIVATE FUNCTIONS PROTOTYPES            *
 *****************************************************/

static void dumpHex(u8 * buf, unsigned count);

/*****************************************************
 *           PUBLIC FUNCTIONS DEFINITIONS            *
 *****************************************************/

/* Selftest to see (by eye :D) if generated bytes are actually random */
int sflc_rand_selftest(void)
{
	u8 * buf;
	int err;

	buf = kmalloc(32, GFP_KERNEL);
	if (!buf) {
		pr_err("Could not allocate random scratchpad\n");
		return -ENOMEM;
	}

	/* Get random bytes the first time */
	err = sflc_rand_getBytes(buf, 32);
	if (err) {
		pr_err("Got error when trying to read random bytes the first time: %d\n", err);
		kfree(buf);
		return err;
	}
	pr_debug("Here's 32 random bytes, fresh fresh!\n");
	dumpHex(buf, 32);

	/* Do it again */
	err = sflc_rand_getBytes(buf, 32);
	if (err) {
		pr_err("Got error when trying to read random bytes the second time: %d\n", err);
		kfree(buf);
		return err;
	}
	pr_debug("Here's another 32 random bytes, fresh fresh pure questi!\n");
	dumpHex(buf, 32);

	pr_info("All well in the crypto rand self test? (Check random bytes)\n");
	kfree(buf);

	return 0;
}

/*****************************************************
 *           PRIVATE FUNCTIONS DEFINITIONS            *
 *****************************************************/

static void dumpHex(u8 * buf, unsigned count)
{
	char * hex;

	hex = kmalloc(6*count + 1, GFP_KERNEL);
	if (!hex) {
		pr_err("Could not allocate hex dump string\n");
		return;
	}

	int i;
	for (i = 0; i < count; i++) {
		sprintf(hex+6*i, "0x%02X, ", buf[i]);
	}

	pr_notice("---- Hex dump ----\n");
	pr_notice("%s", hex);
	pr_notice("---- End of hex dump ----\n");

	kfree(hex);
	return;
}
