# Just a passthrough Makefile that exports the targets defined by the one in
# the src/ directory (there needs to be one to build the module)

default:
	make -C src

debug:
	make -C src debug

install:
	make -C src install

clean:
	make -C src clean
